
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make test'
	@echo
.PHONY: help




test:
	./main.php
.PHONY: test




debian-prepare:
	sudo apt-get install php-cli
.PHONY: debian-prepare
